development:
  adapter: postgresql
  encoding: unicode
  database: project
  pool: 5
  host: localhost
  username: yaroslav
  password: asd1854

test:
  adapter: postgresql
  encoding: unicode
  database: project_test
  pool: 5
  username: yaroslav
  password: asd1854

staging:
  url: <%= ENV['DATABASE_URL'] %>

production:
  url: <%= ENV['DATABASE_URL'] %>
