development:
  adapter: postgresql
  encoding: unicode
  database: slavik
  pool: 5
  host: localhost
  username: slavik
  password: asd1854

test:
  adapter: postgresql
  encoding: unicode
  database: slavik
  pool: 5
  username: slavik
  password: asd1854

staging:
  url: <%= ENV['DATABASE_URL'] %>

production:
  url: <%= ENV['DATABASE_URL'] %>
